### ISSUE TITLE
大佬你好， 我参考你的代码想修改策略租中的节点名，还是没改成功，麻烦你指导一下，谢谢

### ISSUE THREAD

**Issue by bubbleboy11** [yi-Xu-0100/cfw-scripts#143]
```yaml
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点
      - 🚀 手动切换
      - DIRECT
  - name: 🚀 手动切换
    type: select
    proxies:
      - 🇭🇰 Relay_🇨🇳CN-🇭🇰HK_04
      - LT_17
      - LT_18
      - 🇷🇺 Relay_🇷🇺RU-🇷🇺RU_19
```

```js
module.exports.parse = async (raw, { yaml }) => {
    let rawObj = yaml.parse(raw);
    rawObj['proxy-groups'].forEach(proxygroup => {
        proxygroup['proxies'].forEach(proxy => {
            proxy = proxy.replace(/Relay_🇨🇳CN-/ig, ''); //i指忽略大小写， g指全局搜索
        });
    });
    return yaml.stringify(rawObj);
};
```
